# Generated by Django 6.0.3 on 2026-04-06 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'movies',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth0_id', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='MoviePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_backend_app.movie')),
            ],
            options={
                'db_table': 'movie_prices',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_backend_app.user')),
            ],
            options={
                'db_table': 'collections',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_backend_app.user')),
            ],
            options={
                'db_table': 'wishlists',
            },
        ),
        migrations.CreateModel(
            name='CollectionMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_backend_app.collection')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_backend_app.movie')),
            ],
            options={
                'db_table': 'collection_movies',
                'constraints': [models.UniqueConstraint(fields=('collection', 'movie'), name='unique_collection_movie')],
            },
        ),
        migrations.CreateModel(
            name='LikedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_backend_app.collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_backend_app.user')),
            ],
            options={
                'db_table': 'liked_collections',
                'constraints': [models.UniqueConstraint(fields=('user', 'collection'), name='unique_liked_collection')],
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_friend_set', to='django_backend_app.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_backend_app.user')),
            ],
            options={
                'db_table': 'friends',
                'constraints': [models.UniqueConstraint(fields=('user', 'friend'), name='unique_friend')],
            },
        ),
        migrations.CreateModel(
            name='WishlistMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_backend_app.movie')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_backend_app.wishlist')),
            ],
            options={
                'db_table': 'wishlist_movies',
                'constraints': [models.UniqueConstraint(fields=('wishlist', 'movie'), name='unique_wishlist_movie')],
            },
        ),
    ]
