# Generated by Django 6.0.3 on 2026-04-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend_app', '0002_movie_imdb_id_movie_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
