# Generated by Django 6.0.3 on 2026-05-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_backend_app', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]